## <center> CSCI 4190/6908 : Tensorflow Basics</center>

This is a tutorial on fundamental ideas of Tensorflow. This notes is just a starting point. You are encouraged to find out more. The ideal use of this notebook would be as a reference which you keep updating as you learn new things. 

<b>Credits:</b> Content presented in this tutorial is what I have learnt from my teachers, friends and the python community on stackoverflow. 


## Compute Graph ##

* Directed Acyclic Graph
* Nodes having no parent nodes - Placeholders in Tensorflow [Inputs, Outputs]
* Parameters/Transformations/Edges - Variables in Tensorflow 

## The 2  execution patterns

* Build a graph. Use session as the interface to feed in values and to tap values of nodes constructed in the graph.
* Eager - Imperative; works like numpy. You get output as you run. 

In [0]:
import tensorflow as tf
tf.enable_eager_execution()
tfe = tf.contrib.eager

In [0]:
import numpy as np

## Tensor - basic unit of representation

* Tensor:
    * [Formal] An nth-rank tensor in  m-dimensional space is a mathematical object that has n indices and m^n components and obeys certain transformation rules.
    * [Informal] An n-dimensional matrix. 

### tf.Variable, tf.Constant, tf.placeholder

Every tensor has:
    - shape : integer/ None
    - dtype : tf.[int|float][32|64|..]
Main varieties of Tensors 
    - tf.Variable - Trainable; needs to be supplied with an initial_value
    - tf.constant - Constant, Not Trainable; needs value
    - tf.placeholder - External Value, Not Trainable; just shape and dtype. 

In [3]:
tfe.Variable(dtype=tf.float32,initial_value=np.random.randn(10,5))

<tf.Variable 'Variable:0' shape=(10, 5) dtype=float32, numpy=
array([[-1.0136594 , -1.1425868 ,  1.8859718 ,  0.49869332,  0.60236716],
       [ 1.0244449 ,  0.6030814 , -0.03063925, -0.11521606, -0.89523005],
       [ 0.8527448 , -0.09029834,  0.25622925,  0.19526343,  0.10295573],
       [-0.54243517,  0.20789859, -0.42455757,  0.5819857 ,  0.5776305 ],
       [-0.3800926 , -0.28639516, -0.39547843,  0.16242106, -0.55109096],
       [ 0.20466308, -1.8602326 , -0.64831495,  1.5167243 ,  1.3893595 ],
       [-0.43766934,  1.1393421 , -0.8564373 , -1.4611106 , -0.0797151 ],
       [-0.2336373 , -0.11103775,  1.051604  , -0.36328706,  1.2987561 ],
       [ 0.9954128 ,  0.680872  ,  1.1038197 ,  0.33498415, -2.4858701 ],
       [-1.0509274 , -1.8445786 , -1.3696382 , -1.3879672 ,  0.04112148]],
      dtype=float32)>

### Transpose and reshape

In [0]:
x = tf.constant(
    [
       [
           [1,2],
           [3,4]
       ],

       [
           [5,6],
           [7,8]
       ],

       [
           [9,10],
           [11,12]
       ]
    ])
x_2d = tf.constant([[1,2],[3,4]])

In [5]:
tf.shape(x)

<tf.Tensor: id=13, shape=(3,), dtype=int32, numpy=array([3, 2, 2], dtype=int32)>

In [6]:
x.get_shape()

TensorShape([Dimension(3), Dimension(2), Dimension(2)])

Difference?

<b> Transpose </b>

In [7]:
tf.transpose(x)

<tf.Tensor: id=21, shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]], dtype=int32)>

In [8]:
tf.transpose(x,perm=[1,0,2])

<tf.Tensor: id=24, shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[ 3,  4],
        [ 7,  8],
        [11, 12]]], dtype=int32)>

<b> Reshape </b>

In [9]:
tf.reshape(x,[-1,1])

<tf.Tensor: id=27, shape=(12, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int32)>

In [0]:
tf.reshape(x,[1,-1])

<tf.Tensor: id=30, shape=(1, 12), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]], dtype=int32)>

In [0]:
tf.reshape(x,[4,3])

<tf.Tensor: id=33, shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

#### Exercise

Reshape x such that column 1 has [1,2,3,4]; column 2 has [5,6,7,8] and column 3 has [9,10,11,12]. 

In [10]:
tf.transpose(tf.reshape(x,[3,4]))

<tf.Tensor: id=35, shape=(4, 3), dtype=int32, numpy=
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]], dtype=int32)>

## Arithmetic operations 

<b> Addition/Subtraction </b>

In [11]:
x

<tf.Tensor: id=11, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [12]:
x + 1

<tf.Tensor: id=38, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]], dtype=int32)>

In [13]:
x + x

<tf.Tensor: id=40, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]], dtype=int32)>

<b> Multiplication </b>

In [14]:
x * 5

<tf.Tensor: id=43, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5, 10],
        [15, 20]],

       [[25, 30],
        [35, 40]],

       [[45, 50],
        [55, 60]]], dtype=int32)>

In [15]:
x * x

<tf.Tensor: id=45, shape=(3, 2, 2), dtype=int32, numpy=
array([[[  1,   4],
        [  9,  16]],

       [[ 25,  36],
        [ 49,  64]],

       [[ 81, 100],
        [121, 144]]], dtype=int32)>

In [16]:
tf.matmul(x_2d,x_2d)

<tf.Tensor: id=47, shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

<b> Division </b>

In [17]:
from __future__ import division
x_2d/3

<tf.Tensor: id=52, shape=(2, 2), dtype=float64, numpy=
array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])>

In [22]:
x_2d/x_2d

<tf.Tensor: id=68, shape=(2, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.]])>

<b> Broadcasting </b> <br>
Broadcasting is "auto-correction" of one of the arguments in order to bring them to the correct dimensions. 
* Replicates the 1/more dimensions of one or both the tensors to match them.
* From Scipy:
<pre>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when
    * they are equal, or
    * one of them is 1
</pre>
* Makes a best effort to auto-correct; throws error if it cannot. 
* Not applicable to all operators.

In [23]:
x_2d

<tf.Tensor: id=12, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
y = np.array([[1,2]])
print(y.shape)
x_2d + y

(1, 2)


<tf.Tensor: id=75, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 6]], dtype=int32)>

In [26]:
y = np.array([[1],[2]])
print(y.shape)
x_2d + y

(2, 1)


<tf.Tensor: id=78, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [27]:
y = np.array([[1,2]])
print(y.shape)
x * y

(1, 2)


<tf.Tensor: id=81, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 3,  8]],

       [[ 5, 12],
        [ 7, 16]],

       [[ 9, 20],
        [11, 24]]], dtype=int32)>

In [28]:
y = np.array([[1],[2]])
print(y.shape)
x_2d * y

(2, 1)


<tf.Tensor: id=84, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [6, 8]], dtype=int32)>

In [29]:
y = np.array([[1,2]])
print(y.shape)
x_2d / y

(1, 2)


<tf.Tensor: id=89, shape=(2, 2), dtype=float64, numpy=
array([[1., 1.],
       [3., 2.]])>

In [30]:
y = np.array([[1],[2]])
print(y.shape)
x_2d / y

(2, 1)


<tf.Tensor: id=94, shape=(2, 2), dtype=float64, numpy=
array([[1. , 2. ],
       [1.5, 2. ]])>

<b>Perils of broadcasting</b>

In [33]:
p = tf.constant([[1],[2],[3]])
q = tf.constant([[4,5,6]])
print p.shape,q.shape
p+q

(3, 1) (1, 3)


<tf.Tensor: id=106, shape=(3, 3), dtype=int32, numpy=
array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]], dtype=int32)>

## Idea of axis

In [34]:
x_2d

<tf.Tensor: id=12, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [35]:
tf.nn.softmax(tf.cast(x_2d,dtype=tf.float32),axis=1)

<tf.Tensor: id=110, shape=(2, 2), dtype=float32, numpy=
array([[0.26894143, 0.7310586 ],
       [0.26894143, 0.7310586 ]], dtype=float32)>

In [36]:
tf.nn.softmax(tf.cast(x_2d,dtype=tf.float32),axis=0)

<tf.Tensor: id=140, shape=(2, 2), dtype=float32, numpy=
array([[0.11920291, 0.11920291],
       [0.880797  , 0.880797  ]], dtype=float32)>

## Reduce_* functions

In [37]:
tf.reduce_sum(x_2d)

<tf.Tensor: id=143, shape=(), dtype=int32, numpy=10>

In [38]:
tf.reduce_sum(x_2d,axis=0)

<tf.Tensor: id=145, shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [39]:
tf.reduce_sum(x_2d,axis=1)

<tf.Tensor: id=147, shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [40]:
tf.reduce_sum(x_2d,axis=1,keepdims=True)

<tf.Tensor: id=149, shape=(2, 1), dtype=int32, numpy=
array([[3],
       [7]], dtype=int32)>

In [41]:
tf.reduce_sum(x_2d,reduction_indices=[1])

<tf.Tensor: id=152, shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

<b> Exercise </b> <br>
Find the sum of each of the 2x2 matrices of x.

In [42]:
x

<tf.Tensor: id=11, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [45]:
tf.reduce_sum(x, reduction_indices=[1, 2])

<tf.Tensor: id=161, shape=(3,), dtype=int32, numpy=array([10, 26, 42], dtype=int32)>

## tf.boolean_mask

In [46]:
x = tf.constant([1,2,3,4,5,6,7,8,0,0,0,0])
condition = tf.not_equal(x,tf.constant(0))
tf.boolean_mask(x,condition)

<tf.Tensor: id=189, shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

## tf.where 

Use value in x if it is non-zero, else use 10**-5.
<pre> tf.where(condition, A if True, B if False); A and B should have same shape. </pre>

In [51]:
x = tf.constant([1,2,3,4,5,6,7,8,0,0,0,0],dtype=tf.float32)
condition = tf.not_equal(x,tf.constant(0, dtype=tf.float32))
tf.where(condition,x,x+)

InvalidArgumentError: ignored